before_script:
  - "mysql -e 'create database sequelize_test;'"
  - npm install js2coffee@$(echo $JS2COFFEE)
  - npm install sequelize@$(echo $SEQUELIZE)

script:
  - "node_modules/.bin/gulp"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"

env:
  - JS2COFFEE=0.3.5 DIALECT=mysql SEQUELIZE=1.7.10
  - JS2COFFEE=0.3.5 DIALECT=mysql SEQUELIZE=2.0.0-rc8
  - JS2COFFEE=0.3.5 DIALECT=mysql SEQUELIZE=2.0.0
  - JS2COFFEE=0.3.5 DIALECT=sqlite SEQUELIZE=1.7.10
  - JS2COFFEE=0.3.5 DIALECT=sqlite SEQUELIZE=2.0.0-rc8
  - JS2COFFEE=0.3.5 DIALECT=sqlite SEQUELIZE=2.0.0
  - JS2COFFEE=2.0.0 DIALECT=mysql SEQUELIZE=1.7.10
  - JS2COFFEE=2.0.0 DIALECT=mysql SEQUELIZE=2.0.0-rc8
  - JS2COFFEE=2.0.0 DIALECT=mysql SEQUELIZE=2.0.0
  - JS2COFFEE=2.0.0 DIALECT=sqlite SEQUELIZE=1.7.10
  - JS2COFFEE=2.0.0 DIALECT=sqlite SEQUELIZE=2.0.0-rc8
  - JS2COFFEE=2.0.0 DIALECT=sqlite SEQUELIZE=2.0.0



language: node_js
node_js:
- 8.1.3
services:
  - mysql
branches:
  only:
    - development
cache:
  directories:
   - "node_modules"
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

