before_script:
  - "mysql -e 'create database sequelize_test;'"
  - npm install sequelize@$(echo $SEQUELIZE)

script:
  - "node_modules/.bin/gulp"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"

env:
  - DIALECT=mysql SEQUELIZE=4.41.2
  



language: node_js
node_js:
- 8.1.3
services:
  - mysql
branches:
  only:
    - development
cache:
  directories:
   - "node_modules"
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

